name: Deploy to S3
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install dependencies
        run: npm install

      - name: build website
        run: npm run build

      - name: Install AWS CLI
        run: sudo apt-get install -y awscli

      - name: set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: what folder am I in?
        run: pwd

      - name: what folders exist here?
        run: ls -la

      - name: copy to S3
        run: aws s3 sync ./dist/. s3://hotal-cyf